### ISSUE TITLE
Error building daemon.

### ISSUE THREAD

**Issue by ComputerCarl** [phabricator-docker/phabricator#18]
```
Removing intermediate container aa5d9387304f
 ---> c787ae3bba0c
Step 12/14 : RUN git submodule update --init --recursive
 ---> Running in 96694b9dc8a8
fatal: Not a git repository (or any of the parent directories): .git
ERROR: Service 'daemon' failed to build: The command '/bin/sh -c git submodule update --init --recursive' returned a non-zero code: 128
```

**Comment by davidbarratt** [comment]
Did you clone the repo, or download it?

**Comment by davidbarratt** [comment]
unrelated, but you don't have to build it... the image is availble at: https://hub.docker.com/r/phabricator/daemon

**Comment by ComputerCarl** [comment]
Thanks @davidbarratt ! How would I point the main and daemon containers to the db container at `my-phabricator-db`? Are there environment variables which can be set?

**Comment by davidbarratt** [comment]
No they are not, Phabricator cannot be configured with environment variables, I would share a config volume as in the example: https://github.com/phabricator-docker/phabricator/blob/master/docker-compose.yml

**Comment by davidbarratt** [comment]
Has your issue been resolved?

**Comment by ComputerCarl** [comment]
Thanks for your guidance. I haven't resolved it yet, but I will use a config file in the volume.
