### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by mduszenko** [phabricator-docker/phabricator#19]
Hello. We are considering using this image, but there is a small issue concerning TLS.

In order for it to work, Apache needs to have the SSL mod installed which is done by using the command: `a2enmod ssl`, not currenly present in the image.
It is possible to run the command separately, however it has its own maintenance cost. Another option is to modify the image, which is even more problematic maintenance-wise.

Do you think the mod can be added to the image? Or maybe there is another way of approaching this problem?

**Comment by davidbarratt** [comment]
Phabricator does not list `mod_ssl` as a requirement, so it should not be included in this image.

However, you can add this  yourself pretty easily by creating a new `Dockerfile` with something like this:
```dockerfile
FROM phabricator/phabricator

RUN a2enmod ssl
```

You can then build the image with [docker build](https://docs.docker.com/engine/reference/commandline/build/). Will that meet your needs?

**Comment by mduszenko** [comment]
Thank you for the answer.
This was one of the solutions we considered. We wanted to see if there is a better way.

 I think we will use the method you mentioned.

**Comment by davidbarratt** [comment]
Unfortunately, any image that is shared can't add everything everyone needs. Extending images with `FROM` is typically the best way to change images before deploying them. :)

**Comment by davidbarratt** [comment]
Another solution, one that I implement, is to use a reverse proxy (either k8s has one built in, or you could use a `nginx` image or something like that) to terminal the TLS before forwarding the request to phabricator.
