### ISSUE TITLE
phabricator.daemon can't be connection mariadb container,how to correct?

### ISSUE THREAD

**Issue by empiregeneral** [phabricator-docker/phabricator#32]
root@63021b62cca1:/var/www/phabricator/bin# ./phd start
[2020-06-28 09:46:09] PHLOG: 'Retrying database connection to "localhost" after connection failure (attempt 1; "AphrontConnectionQueryException"; error #2002): Attempt to connect to root@localhost failed with error #2002: No such file or directory.' at [/var/www/phabricator/src/infrastructure/storage/connection/mysql/AphrontBaseMySQLDatabaseConnection.php:135]
[2020-06-28 09:46:09] PHLOG: 'Retrying database connection to "localhost" after connection failure (attempt 2; "AphrontConnectionQueryException"; error #2002): Attempt to connect to root@localhost failed with error #2002: No such file or directory.' at [/var/www/phabricator/src/infrastructure/storage/connection/mysql/AphrontBaseMySQLDatabaseConnection.php:135]
[2020-06-28 09:46:09] EXCEPTION: (PhabricatorClusterStrandedException) Unable to establish a connection to any database host (while trying "phabricator_config"). All masters and replicas are completely unreachable.

AphrontConnectionQueryException: Attempt to connect to root@localhost failed with error #2002: No such file or directory. at [<phabricator>/src/infrastructure/storage/lisk/PhabricatorLiskDAO.php:177]
arcanist(), phabricator()
  #0 PhabricatorLiskDAO::raiseUnreachable(string, AphrontConnectionQueryException) called at [<phabricator>/src/infrastructure/storage/lisk/PhabricatorLiskDAO.php:134]
  #1 PhabricatorLiskDAO::newClusterConnection(string, string, string) called at [<phabricator>/src/infrastructure/storage/lisk/PhabricatorLiskDAO.php:70]
  #2 PhabricatorLiskDAO::establishLiveConnection(string) called at [<phabricator>/src/infrastructure/storage/lisk/LiskDAO.php:841]
  #3 LiskDAO::establishConnection(string) called at [<phabricator>/src/infrastructure/storage/lisk/LiskDAO.php:518]
  #4 LiskDAO::loadRawDataWhere(string, string) called at [<phabricator>/src/infrastructure/storage/lisk/LiskDAO.php:478]
  #5 LiskDAO::loadAllWhere(string, string) called at [<phabricator>/src/infrastructure/env/PhabricatorConfigDatabaseSource.php:18]
  #6 PhabricatorConfigDatabaseSource::loadConfig(string) called at [<phabricator>/src/infrastructure/env/PhabricatorConfigDatabaseSource.php:7]
  #7 PhabricatorConfigDatabaseSource::__construct(string) called at [<phabricator>/src/infrastructure/env/PhabricatorEnv.php:262]
  #8 PhabricatorEnv::buildConfigurationSourceStack(boolean) called at [<phabricator>/src/infrastructure/env/PhabricatorEnv.php:95]
  #9 PhabricatorEnv::initializeCommonEnvironment(boolean) called at [<phabricator>/src/infrastructure/env/PhabricatorEnv.php:75]
  #10 PhabricatorEnv::initializeScriptEnvironment(boolean) called at [<phabricator>/scripts/init/lib.php:26]
  #11 init_phabricator_script(array) called at [<phabricator>/scripts/init/init-script.php:9]
  #12 require_once(string) called at [<phabricator>/scripts/__init_script__.php:3]
  #13 require_once(string) called at [<phabricator>/scripts/daemon/manage_daemons.php:5]

**Comment by davidbarratt** [comment]
Phabricator Daemon should start whenever the container starts:
https://github.com/phabricator-docker/phabricator/blob/86a3b109b88d325f82fd39050cfa123d391729ce/Dockerfile.daemon#L117-L118
That container needs to be connected to the same config file:
https://github.com/phabricator-docker/phabricator/blob/86a3b109b88d325f82fd39050cfa123d391729ce/docker-compose.yml#L19
as the main conainer:
https://github.com/phabricator-docker/phabricator/blob/86a3b109b88d325f82fd39050cfa123d391729ce/docker-compose.yml#L7

**Comment by gusarg81** [comment]
Hi, I have the same problem, and the only thing I've changed in docker_compose.json is the mariadb passwd and the port to 3003. 
phabricator_daemon_1 does not start because of that either:

> [2020-07-23 12:42:24] EXCEPTION: (PhabricatorClusterStrandedException) Unable to establish a connection to any database host (while trying "phabricator_config"). All masters and replicas are completely unreachable.
> 
> AphrontInvalidCredentialsQueryException: #1045: Access denied for user 'root'@'172.20.0.1' (using password: YES) at [<phabricator>/src/infrastructure/storage/lisk/PhabricatorLiskDAO.php:177]

**Comment by baldonharris** [comment]
Hi. Any updates on how to resolve this? Having the same issue with @gusarg81

**Comment by davidbarratt** [comment]
Did you set phabricator's configuration as I mentioned in https://github.com/phabricator-docker/phabricator/issues/32#issuecomment-650751618 ?

You cannot configuration phabricator through environment variables, it **must** be configured through the config file.

**Comment by davidbarratt** [comment]
Please let me know if you have any other problems. :)
