### ISSUE TITLE
Phabricator Docker doesn’t start daemon

### ISSUE THREAD

**Issue by andrew-dixon** [phabricator-docker/phabricator#41]
Whenever the container is restarted the daemon isn’t started by default and we have to go into the container and run:

```./bin/phd start```

manually. Is there something we are missing about how to get this to start on boot of the container?

**Comment by davidbarratt** [comment]
There is a seperate container for that:
https://hub.docker.com/r/phabricator/daemon

Seperating them allows you to scale the web servers horizontally and leave the daemon as a single instance.

**Comment by davidbarratt** [comment]
For anyone else who arrives at this issue, all of the published images can be seen here:
https://hub.docker.com/u/phabricator
