### ISSUE TITLE
Can Not Connect to MySQL

### ISSUE THREAD

**Issue by Vanson** [phabricator-docker/phabricator#42]
Unable to connect to MySQL!

Unable to establish a connection to any database host (while trying "phabricator_config"). All masters and replicas are completely unreachable.

AphrontConnectionQueryException: Attempt to connect to root@localhost failed with error #2002: No such file or directory.

Make sure Phabricator and MySQL are correctly configured.

phabricator/phabricator:latest
DIGEST:sha256:f1a89bc3a58eaec79ff5e37525bfc26798d7127a331874d409427bb0db2e4136

**Comment by davidbarratt** [comment]
@Vanson you need to configure Phabricator on how to connect to MySQL. Unfortunately Phabricator does not read configuration from environment variables.

**Comment by Vanson** [comment]
> @Vanson you need to configure Phabricator on how to connect to MySQL. Unfortunately Phabricator does not read configuration from environment variables.

Thanks for the reply, I am going to modify it, this issue can be closed
