### ISSUE TITLE
Update docker images

### ISSUE THREAD

**Issue by d0niek** [phabricator-docker/phabricator#51]
Hi!

I want to ask why you don't update a docker images when new phabricator update appears?

If someone is using your repository and is building images by his self then the latest code of phabricator will be downloaded but if someone (like me) is using your pre-build images then the code of phabricator is old.

I can add `RUN git submodule update --init --recursive` to the end of my Dockerfiles but it would be nice if your images would have the latest code.

**Comment by davidbarratt** [comment]
They should have the latest code.
https://github.com/phabricator-docker/phabricator/blob/0d82a38bfb416f465215a0a80d12ca2766d3df28/.github/workflows/update.yml#L22-L30

**Comment by davidbarratt** [comment]
Oh weird it looks like this action isn't running for some reason...
https://github.com/phabricator-docker/phabricator/blob/master/.github/workflows/build.yml

**Comment by davidbarratt** [comment]
Pushed an emtpy commit and that has kicked it... I don't understand why the update wouldn't have caused it to execute though. :/

**Comment by davidbarratt** [comment]
Ugh. https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

**Comment by davidbarratt** [comment]
Theoretically this should fix it
https://github.com/phabricator-docker/phabricator/commit/7b94dad38b4bfb8ee6e7b53f8e4d06a56583ebd1

**Comment by davidbarratt** [comment]
Sorry about the image getting out of sync and thanks for brining it to my attention! :)
